### ISSUE TITLE
It is nonsense that the Record constructor's argument is a single object

### ISSUE THREAD

**Issue by the-red** [kintone/kintone-js-sdk#114]
I am trying v0.5.0.

It is very good that each function argument is a single object.

However, I think it is nonsense that the Record constructor's argument is also a single object 😫 
https://github.com/kintone/kintone-js-sdk/blob/v0.5.0/src/base/module/record/Record.js#L26
```
new Record({connection: kintoneConnection})
```

I think there is always one argument for Record constructor. 
Don't you think that this is enough?
```
new Record(kintoneConnection)
```

仕様を統一したい気持ちは理解できるのですが、
シンプルに済んでいる部分に関しては、
「使い方が無駄に面倒くさくなる」方へは向かわないで頂きたい・・・
ご検討お願いします 🙏

**Comment by latica-jp** [comment]
Could you explain why you decided to turn all args into a single object? 
I'm just curious about it 🙂

**Comment by youtr-s** [comment]
@the-red 
お返事が遅れてしまい大変申し訳ございません。

ご意見承りました。
こちら改めて社内で議論させていただき、
今後の開発の参考とさせていただきます。

@latica-jp 
Sorry for replying so late.

The reasons why we decided to turn all args into a single object are
・avoid passing too many arguments to call a function
・be easy to update function with argument changes

Thank you.

**Comment by latica-jp** [comment]
@youtr-s 
I got it. Thanks for your response!
