### ISSUE TITLE
Creating a connection using a guest space ID does not change the API URL.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone/kintone-js-sdk#144]
Specifying a guest space ID does not work when creating a connection instance.
The API URL is accessed as a regular URL, not for guest space.

At this time, "NaN" is set in the connection instance guestSpaceID property.

```
const connection = new kintoneJSSDK.Connection({guestSpaceID: 4});
console.log(connection.guestSpaceID); // => NaN

const kintoneRecord = new kintoneJSSDK.Record(connection);
kintoneRecord.getAllRecordsByQuery(app, query,fields,totalCount);
// ⇒ゲストスペース内のアプリを操作する場合は、リクエストの送信先を「/k/guest/（ゲストスペースのID）/v1/...」にします。
```

**Comment by trinhhunganh** [comment]
@Yanchi4425 
> const connection = new kintoneJSSDK.Connection({guestSpaceID: 4});
> console.log(connection.guestSpaceID); // => NaN

I just tried on my environment and it shows "4" in console as expected.
Can you please provide more details on how you installed kintone-js-sdk and how do you use it in your project?

Thank you!

**Comment by Yanchi4425** [comment]
I was using version 0.4.2.
When the same source was executed with the current latest version (v0.6.1), it worked normally.

Thank you.

**Comment by trinhhunganh** [comment]
> I was using version 0.4.2.
> When the same source was executed with the current latest version (v0.6.1), it worked normally.
> 
> Thank you.

I see, glad it works for you now!
