### ISSUE TITLE
(add|update|delete)Recordsでの100〜2000件処理

### ISSUE THREAD

**Issue by the-red** [kintone/kintone-js-sdk#161]
kintoneUtilityでは、
postRecords、putRcords、deleteRecordsは
「100件以上処理可能、2000件上限」
だったと思いますが、
kintone-js-sdk で
addRcords、updateRecords、deleteRecordsでは、REST APIの標準と同じ100件までしか処理できなくなっているようですね。
以前のような「2000件まで処理可能、ロールバック対応」という概念は、js-sdkには存在しないなでしょうか？

気になったのは、
addAllRecords、updateAllRecords、deleteAllRecordsByQueryのドキュメントにこう書かれていることです。

> Can xxx over 2000 records, but can't do the rollback.

この解釈として、以下のどちらでしょう？
* over 100のすべきところ書き間違い
* 1〜2000はロールバック可能、2001〜ロールバック不可能と自動で切り替わる
* その他

kintoneUtilityからの移行時に、この辺の仕様をしっかり把握しておかないと安全に移行できないので、教えてください。（特にdeleteRecordsは関数名が同じなので、普通に書き換えたら100件越えエラーが起きてびっくりしました。)

**Comment by the-red** [comment]
コード読みました。
https://github.com/kintone/kintone-js-sdk/blob/v0.7.0/src/base/module/record/Record.js#L201-L215

ここから察するに、
「1〜2000はロールバック可能、2001〜ロールバック不可能と自動で切り替わる」
が一番近いですね。

bulkRequestを再帰的に行っているので、
```
(REST APIの上限100) * (bulkの同時実行上限20) = 2000
```
というのが一回のbulkRequestの単位。それが線形に処理される。

そのため、
* 最初の2000件のどこかで失敗したら、完全にロールバックされる
* 2001～4000件目で失敗したら、最初の2000件は戻らず、2001件目以降はロールバックされる
* 4001～6000件目で失敗したら、最初の4000件は戻らず、4001件目以降はロールバックされる
* 以下8001, 10001...と同じ条件

と理解しました。間違いないでしょうか？？

(add|update|delete)AllRecords系の仕様自体は、[kintoneUtility時代から変わらない](https://github.com/kintone/kintoneUtility/blob/master/src/js/rest/postAllRecords.js#L27-L46)のですね。

(add|update|delete)Recordsの仕様としては、以下のように変わっているのが確認できました。
* kintoneUtility: [1回だけbulkRequestする](https://github.com/kintone/kintoneUtility/blob/d3823d5682f04fa8ad170918edf26e63bac97c16/src/js/rest/postRecords.js#L29-L36)(上限100 * 20 = 2000)
* kintone-js-sdk: [1回だけそのまんまRequestする](https://github.com/kintone/kintone-js-sdk/blob/v0.7.0/src/base/module/record/Record.js#L189-L193)(上限100)

現在のjs-sdkのドキュメントは、唐突に「over 2000」という数字が出てきて大変分かりにくいです。以下の2点が伝わるような表現でぜひお願いします。

* (add|update|delete)Recordsは標準と同じ100件までしか処理できない
* (add|update|delete)AllRecordsは101件以上を上限なしで処理可能、ロールバックは2000件単位

**Comment by youtr-s** [comment]
@the-red 
issue登録ありがとうございます。
お問い合わせ頂いた(add|update|delete)AllRecords系の仕様ですが

>最初の2000件のどこかで失敗したら、完全にロールバックされる
>2001～4000件目で失敗したら、最初の2000件は戻らず、2001件目以降はロールバックされる
>4001～6000件目で失敗したら、最初の4000件は戻らず、4001件目以降はロールバックされる
>以下8001, 10001...と同じ条件
>と理解しました。間違いないでしょうか？？

上記の認識で相違ございません。

またご指摘いただいたドキュメントの文言についても、
今後修正予定ですのでしばらくお待ち下さい。

**Comment by the-red** [comment]
よろしくお願いします！
（ボソッ）日本語ドキュメントもぜひ・・・

**Comment by youtr-s** [comment]
連絡が遅くなりましたがこちら対応させていただきました。
https://github.com/kintone/kintone-js-sdk/commit/3073ca4e5bdcc06ce8edbc743e11fb873c62c221

(ドキュメントの日本語対応についてはもうしばらくお待ち下さい。。。)
