### ISSUE TITLE
To get recursively a list of over 100 apps.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone/kintone-js-sdk#193]
I want a feature that recursively retrieves more than 100 apps.
(e.g. kintoneApp.getAllApps)

**Comment by miyass** [comment]
@Yanchi4425 
Thank you for your feedback!
As described in the README, kintone-js-sdk will be deprecated.
We will consider about your request function to develop @kintone/rest-api-client.
For more information about @kintone/rest-api-client, please see its [README](https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/README.md).
Thank you for your time.

**Comment by Yanchi4425** [comment]
Oh, I didn't know that.
I understood.
