### ISSUE TITLE
Please support OAuth token authorization

### ISSUE THREAD

**Issue by the-red** [kintone/kintone-js-sdk#32]
I'd like to use OAuth token authorization via kintone-js-sdk as follows.

```js
    let oauthTokenString = '{your_token}';
    kintoneAuth.setOauthToken(oauthTokenString);
```
I can create OAuth token by my tool [Gyuma](https://github.com/goqoo-on-kintone/gyuma).
So it is OK if you implement `setOauthToken()` function.
Please support :pray:

**Comment by trung-doan** [comment]
We will consider to kintone-js-sdk correspondence.
Thank you!
