### ISSUE TITLE
getAllRecordsByCursorのエラーについて

### ISSUE THREAD

**Issue by kana170612** [kintone/kintone-js-sdk#75]
kintone js SDK v0.4.0

わざとエラーを出してcatchしてみましたが、
`TypeError: err.get is not a function`
となりました。
エラーがKintoneAPIExceptionでthrowされていないようです。

試してみたのは以下のコード。（サンプルコードそのまま）
```
kintoneRecord.getAllRecordsByCursor(rcOption).then((rsp) => {
    console.log(rsp);
}).catch((err) => {
// This SDK return err with KintoneAPIException
      console.log(err.get());
});
```
#

**Comment by youtr-s** [comment]
お問い合わせありがとうございます。

今回調査した結果、存在しないappIDを指定するなどのカーソルが作成できないような不正な値をパラメータにセットすると
お問い合わせ頂いた様な現象が発生することが確認できました。

もし上記の様な条件以外で今回のお問い合わせ頂いた現象が発生する様でしたら、
rcOptionの設定内容など、もう少し詳細な発生条件をご教授いただきたく存じます。

**Comment by kana170612** [comment]
cOptionの設定内容です。
queryに存在しないフィールドを使用してみました。
```
        var rcOption = {
            app: appid, //存在するアプリＩＤ
            query: 'testField = "123"' //存在しないフィールド
          };
```

**Comment by youtr-s** [comment]
ご返信いただきありがとうございます。

確認したところ、不正なクエリを指定した際にもお問い合わせ頂いた様な現象が発生することが確認できました。
こちらについては今後の開発計画の中で対応を検討致します。

**Comment by trinhhunganh** [comment]
Fixed in https://github.com/kintone/kintone-js-sdk/releases/tag/v0.4.2
