### ISSUE TITLE
'414 Request-URI Too Large' via Api Token Authentication

### ISSUE THREAD

**Issue by the-red** [kintone/kintone-js-sdk#77]
本文は日本語で行きます。

webpackでビルドしてkintoneカスタマイズ用にjs-sdkを使ってますが、
getAllRecordsByQuery() で長めのクエリを使ってレコードGETする場合、
セッション認証ではうまくGETできるのに、
APIトークン認証を使うと、`414 Request-URI Too Large`とエラーが出ます。

js-sdkのコードはまだ読めてないのですが、
おそらくセッション認証の場合は`kintone.api()`でリクエストされるので、
JavaScript APIの仕様によりX-HTTP-Method-Overrideヘッダが自動付与されるのでうまくいっているのかと思います。
https://developer.cybozu.io/hc/ja/articles/201941754#step9

試してないですが、パスワード認証でも同じくエラーになる気がしてます。
セッション認証以外の場合でも、クエリが長い場合はX-HTTP-Method-Overrideを使ったリクエストに自動で切り替えてもらえないでしょうか？

よろしくお願いします。

**Comment by the-red** [comment]
今回のクエリの長さは48,986文字でした。
セッション認証だと普通にうまく動きます。

**Comment by trinhhunganh** [comment]
Fixed in https://github.com/kintone/kintone-js-sdk/releases/tag/v0.5.0
Thank you!
